services:
  - type: web
    name: lead-finder
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn lead_finder:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: FLASK_ENV
        value: production
