services:
  - type: web
    name: lead-finder
    env: python
    python_version: 3.11.6
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn lead_finder:app --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
